//LOCALHOST for planets
### LOCAL Get api-docs
GET http://localhost:3000/api-docs 

### GET all planets
GET http://localhost:3000/planets 

### GET planet by ID
GET http://localhost:3000/planets/653444dcbd87e66f0e061e3e HTTP/1.1

### CREATE New planet
POST http://localhost:3000/planet HTTP/1.1
content-type: application/json

{
    "name":"Neptune",
    "numberOrder":"8", 
    "distanceFromSun":"4,501,000,000 km (2,796,791,736 mi)", 
    "temperature":"-201 °C (-331 °F)",
    "dayLength":"16 Earth hours", 
    "yearLength":"165 Earth years", 
     "numberOfMoons":"14"
}

### Delete Appointment - MUST UPDATE ID!!!
DELETE http://localhost:3000/planet/653444dcbd87e66f0e061e45



//LOCALHOST for Spacecraft
### LOCAL Get api-docs
GET http://localhost:3000/api-docs 

### GET all Spacecraft
GET http://localhost:3000/spacecraft 

### GET Spacecraft by ID
GET http://localhost:3000/spacecraft/655c5cd70f0c052897baadce HTTP/1.1

### CREATE New Spacecraft
POST http://localhost:3000/spacecraft HTTP/1.1
content-type: application/json

{
    "objective":"Study the Moon's environment",
    "spacecraft":"Saturn V/ Apollo 16 Subsatellite",
    "spacecraftMass":"36.3 kilograms",
    "missionDesign":"NASA-Office of Manned Space Flight",
    "launchDateTime":"Apr. 24, 1972",
    "launchSite":"Cape Canaveral, Florida, USA | Launch Complex 39A",
    "scientificInstruments":"magnetometer, S-band transponder, charged-particle detectors"
}

### Delete Appointment - MUST UPDATE ID!!!
DELETE http://localhost:3000/spacecraft/655c5cd70f0c052897baadce"




//PRODUCTION for Planets
### RENDER Get api-docs
GET https://planetsproject.onrender.com/api-docs 

### GET all planets
GET https://planetsproject.onrender.com/planets 

### GET planet by ID
GET https://planetsproject.onrender.com/planets/653444dcbd87e66f0e061e3e HTTP/1.1

### CREATE New planet
POST https://planetsproject.onrender.com/planet HTTP/1.1
content-type: application/json

{
    "name":"Neptune",
    "numberOrder":"8", 
    "distanceFromSun":"4,501,000,000 km (2,796,791,736 mi)", 
    "temperature":"-201 °C (-331 °F)",
    "dayLength":"16 Earth hours", 
    "yearLength":"165 Earth years", 
     "numberOfMoons":"14"
}

### Delete Appointment - MUST UPDATE ID!!!
DELETE https://planetsproject.onrender.com/planet/653444dcbd87e66f0e061e45



//PRODUCTION for Spacecraft
### RENDER Get api-docs
GET https://planetsproject.onrender.com/api-docs 

### GET all Spacecraft
GET https://planetsproject.onrender.com/spacecraft 

### GET Spacecraft by ID
GET https://planetsproject.onrender.com/spacecraft/6534488bbd87e66f0e0c83ae HTTP/1.1

### CREATE New planet
POST https://planetsproject.onrender.com/spacecraft HTTP/1.1
content-type: application/json

{
    "objective":"Study the Moon's environment",
    "spacecraft":"Saturn V/ Apollo 16 Subsatellite",
    "spacecraftMass":"36.3 kilograms",
    "missionDesign":"NASA-Office of Manned Space Flight",
    "launchDateTime":"Apr. 24, 1972",
    "launchSite":"Cape Canaveral, Florida, USA | Launch Complex 39A",
    "scientificInstruments":"magnetometer, S-band transponder, charged-particle detectors"
}

### Delete Appointment - MUST UPDATE ID!!!
DELETE https://planetsproject.onrender.com/spacecraft/6534488bbd87e66f0e0c83ae


