//LOCALHOST
###
GET http://localhost:3000 HTTP/1.1

###Get all planets
GET http://localhost:3000/planets HTTP/1.1




//PRODUCTION Deploy
### Get all planets
GET https://personalproject-mpza.onrender.com/planets


### Get planets by id
GET https://personalproject-mpza.onrender.com/planets/652b4b28910e08ba7ffb46b4

###
GET https://personalproject-mpza.onrender.com/planets/652b4b28910e08ba7ffb46b5

###
GET https://personalproject-mpza.onrender.com/planets/652b4b28910e08ba7ffb46b6

###
GET https://personalproject-mpza.onrender.com/planets/652b4b28910e08ba7ffb46b7

###
GET https://personalproject-mpza.onrender.com/planets/652b4b28910e08ba7ffb46b8

###
GET https://personalproject-mpza.onrender.com/planets/652b4b28910e08ba7ffb46b9

###
GET https://personalproject-mpza.onrender.com/planets/652b4b28910e08ba7ffb46ba

###
GET https://personalproject-mpza.onrender.com/planets/652b4b28910e08ba7ffb46bb